# Generated by Django 4.2.8 on 2025-11-04 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='color',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Đực'), ('F', 'Cái')], max_length=1),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='species',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
