# Generated by Django 4.2.8 on 2025-11-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_remove_badge_icon_emoji'),
        ('profiles', '0002_alter_petprofile_options_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displayed_by', to='badge.badge'),
        ),
    ]
