# Generated by Django 4.2.8 on 2025-11-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_display_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='display_badge',
        ),
    ]
