# Generated by Django 5.2.7 on 2025-11-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_userbadgeprogress'),
        ('profiles', '0004_remove_userprofile_display_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_displaying', to='badge.badge', verbose_name='Danh hiệu hiển thị'),
        ),
    ]
