# Generated by Django 4.2.8 on 2025-11-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_alter_event_date_alter_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100, verbose_name='Số lượng người tham gia tối đa'),
        ),
    ]
