# Generated by Django 4.2.8 on 2025-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_alter_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng người tham gia tối đa'),
        ),
    ]
