# Generated by Django 4.2.8 on 2025-11-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh hiệu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả danh hiệu')),
                ('type', models.CharField(choices=[('post', 'Bài viết'), ('comment', 'Bình luận'), ('reaction', 'Tương tác')], default='post', help_text='Chọn loại hành động dùng để tính tiến trình (bài viết, bình luận, tương tác)', max_length=20, verbose_name='Loại danh hiệu')),
                ('target', models.PositiveIntegerField(default=1, help_text='Số lượng cần đạt để hoàn thành danh hiệu', verbose_name='Mục tiêu cần đạt')),
                ('color', models.CharField(choices=[('gold', 'Vàng'), ('blue', 'Xanh dương'), ('green', 'Xanh lá'), ('red', 'Đỏ'), ('cyan', 'Xanh ngọc'), ('lime', 'Xanh nhạt')], default='blue', max_length=20, verbose_name='Màu hiển thị')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('achieved_count', models.IntegerField(default=0, verbose_name='Số người đã đạt')),
            ],
        ),
    ]
