# Generated by Django 4.2.8 on 2025-11-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon_emoji',
            field=models.CharField(default='TROPHY', max_length=10, verbose_name='Icon emoji'),
        ),
    ]
