# Generated by Django 4.2.8 on 2025-11-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_badge_icon_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon_emoji',
        ),
    ]
