# Generated by Django 4.2.8 on 2025-11-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_remove_badge_icon_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, choices=[('TROPHY', 'TROPHY'), ('STAR', 'STAR'), ('FIRE', 'FIRE'), ('LIGHTNING', 'LIGHTNING'), ('HEART', 'HEART'), ('CHAT', 'CHAT'), ('ROCKET', 'ROCKET'), ('CROWN', 'CROWN'), ('GIFT', 'GIFT'), ('FLAG', 'FLAG'), ('MEOW', 'MEOW'), ('PAW', 'PAW')], default='TROPHY', max_length=20, verbose_name='Icon danh hiệu'),
        ),
    ]
