# Generated by Django 5.2.7 on 2025-11-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_userbadgeprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='🏆', help_text='Chọn icon hiển thị cho danh hiệu.', max_length=5, verbose_name='Icon danh hiệu'),
        ),
    ]
