# Generated by Django 5.2.7 on 2025-11-02 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_comment',
            fields=[
                ('rpcmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('deleted', 'Đã xóa nội dung'), ('dismissed', 'Bác bỏ')], default='pending', max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reports_post',
            fields=[
                ('rppost_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('deleted', 'Đã xóa nội dung'), ('dismissed', 'Bác bỏ')], default='pending', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
