# Generated by Django 4.2.8 on 2025-11-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('chamsoc', 'Chăm sóc thú cưng'), ('dilac', 'Đi lạc'), ('dinhduong', 'Dinh Dưỡng'), ('kienthuc', 'Kiến thức'), ('lamdep', 'Làm đẹp')], default='chamsoc', max_length=100),
        ),
    ]
