# Generated by Django 5.2.7 on 2025-11-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_reportscomment_comment_alter_reportspost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('dinhduong', 'Dinh dưỡng & Thức ăn'), ('suckhoe_benhly', 'Sức khỏe & Bệnh lý'), ('huanluyen', 'Huấn luyện & Hành vi'), ('cham_soc', 'Chăm sóc & Vệ sinh'), ('capcuu', 'Cấp cứu & Khẩn cấp'), ('hinh_anh', 'Khoe ảnh Thú cưng'), ('review', 'Đánh giá Dịch vụ & SP'), ('pet_friendly', 'Địa điểm Pet-Friendly'), ('cuu_ho', 'Cứu hộ & Nhận nuôi'), ('tim_nha', 'Tìm nhà / Phối giống'), ('ky_niem', 'Kỷ niệm & Tạm biệt'), ('chung', 'Thảo luận chung')], max_length=50),
        ),
    ]
