# Generated by Django 5.2.8 on 2025-11-29 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forbiddenkeyword',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='forbiddenkeyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forbiddenkeyword',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
